main: net.hypexmon5ter.pm.PlayerMention
name: PlayerMention
author: HYPExMon5ter
version: 3.7
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Essentials, FactionChat, mcMMO, SuperVanish, PremiumVanish, Skript, Marriage]

commands:
  playermention:
    description: This is the main command for PlayerMention.
    aliases: /pm